global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['taskkeep-backend:8000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['taskkeep-nginx:80']
